### ISSUE TITLE
Github Oauth2 404 page not found: PWD in own infrastructure

### ISSUE THREAD

**Issue by eshnil2000** [play-with-docker/play-with-docker#284]
Hi:
I'm trying to enable github oauth2.
My setting on github website:
`Homepage URL:
http://mydomain.com
`

`Callback URL:
http://mydomain.com/oauth/providers/github/callback 
`
I manually checked the github oauth2 is functioning correctly:
https://github.com/login/oauth/authorize?scope=user:email&client_id=xxx

this successfully takes me to github login page, and redirects me to: 
http://mydomain.com/oauth/providers/github/callback?code=xxx

I also manually tested the callback by providing the "state", I was redirected back to:
http://mydomain.com/oauth/providers/github/callback?code=xxx&state=bdimv14ecvqg0b7kr7h0

In the browser console (firefox), i saw a message:
_The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature._

My settings in PWD:
I added the following info myClientID, myClientSecret  in handlers/bootstrap.go to enable oauth2

`config.Providers[p.Id] = map[string]*oauth2.Config{
        "github": {
        ClientID : "myClientID",
        ClientSecret: "myClientSecret" },
        } `

When I browse to the landing page, i see "github" in the dropdown.

On selecting github, I'm redirected to:
`
http://mydomain.com/oauth/providers/github/login/
`

which immediately redirects to:
`
http://mydomain.com/oauth/providers/github/?client_id=XXX&nonce=8a1312f1-bb78-4d6d-91ac-4a439f2fc237&redirect_uri=http%3A%2F%2Fmydomain.com%2Foauth%2Fproviders%2Fgithub%2Fcallback&response_type=code&state=bdiljpcecvqg0b7kr7dg
`

And i get a 404 page not found.

Shouldn't it redirect to the Github endpoint for authentication? Seems like the "host" variable in handlers/login.go , func Login(..){}  is not redirecting to github, instead redirecting to mydomain.com.

`
provider.RedirectURL = fmt.Sprintf("%s://%s/oauth/providers/%s/callback", scheme, host, providerName)

url := provider.AuthCodeURL(loginRequest.Id, oauth2.SetAuthURLParam("nonce", uuid.NewV4().String()))

http.Redirect(rw, req, url, http.StatusFound) 
`
My vendor/golang.org/x/oauth2/github folder has github.go file:

`
// Endpoint is Github's OAuth 2.0 endpoint.
var Endpoint = oauth2.Endpoint{
        AuthURL:  "https://github.com/login/oauth/authorize",
        TokenURL: "https://github.com/login/oauth/access_token",
}
`

**Comment by eshnil2000** [comment]
Resolved. My error, didn't set the securecookie value correctly

**Comment by manuken** [comment]
Hi @eshnil2000 I'm running on the exact same issue. I've set the for securecookie on config/config.go but still getting the 404 error. Could you explain how did you solve your issue?

**Comment by eshnil2000** [comment]
@manuken what exactly did you set in config/config.go? 
To enable Oauth2: 

1. config/config.go, set hash keys to 32 bytes: flag.StringVar(&CookieHashKey, "cookie-hash-key","32-bytes-here", "Hash key to use to validate cookies") flag.StringVar(&CookieBlockKey, "cookie-block-key", "32-bytes-here", "Block key to use to encrypt cookies")

2. handlers/bootstrap.go, set the following import "os"
func initOauthProviders(p types.Playground) { config.Providers[p.Id] = map[string]oauth2.Config{ "github": { ClientID : "ClientID", ClientSecret: "ClientSecret" }
